name: Nextflow Pipeline Test

on:
  workflow_call:
    inputs:
      nextflow_version:
        description: 'Nextflow version to use'
        required: false
        type: string
        default: '24.10.3'
      java_version:
        description: 'Java version to use'
        required: false
        type: string
        default: '17'

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          echo "matrix=$(find data/test -name "test*.yml" -type f | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  test:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_file: ${{ fromJson(needs.discover.outputs.matrix) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ inputs.nextflow_version }}

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Run custom setup script
        run: |
          if [ -f ".github/workflows/setup.sh" ]; then
            bash ./.github/workflows/setup.sh
          fi

      - name: Run test
        run: |
          echo "Running test with ${{ matrix.test_file }}"
          nextflow run . -params-file "${{ matrix.test_file }}"
